sprite_icons.png:
  city:
    width: 20
    height: 34
    y: 30
    alt: City/Suburb
  property_hl:
    width: 20
    height: 34
    y: 94
  weather_clouds:
    y: 0
    width: 16
    height: 16
  weather_cloudy:
    y: 66
    width: 16
    height: 16
  weather_lightning:
    y: 132
    width: 16
    height: 16
  weather_rain:
    y: 198
    width: 16
    height: 16
  weather_snow:
    y: 264
    width: 16
    height: 16
  weather_sun:
    y: 330
    width: 16
    height: 16

